"""cria_tabela_associativa_item_servicos

Revision ID: 00657290da5a
Revises: 946f9c56dc60
Create Date: 2026-10-02 18:12:29.868319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00657290da5a'
down_revision: Union[str, Sequence[str], None] = '946f9c56dc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemservico',
    sa.Column('tempo_hora', sa.Integer(), nullable=False),
    sa.Column('valor_hora', sa.Float(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordemservico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemservico')
    # ### end Alembic commands ###
