"""cria_tabela_cliente

Revision ID: 47e764a440a2
Revises: 
Create Date: 2026-10-02 14:34:32.832123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47e764a440a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_cliente_nome'), 'cliente', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cliente_nome'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
