"""cria_tabela_pagamento_diagnostico

Revision ID: 4abf1bc8e421
Revises: 590ff7d8fd5b
Create Date: 2026-10-02 19:03:12.671331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4abf1bc8e421'
down_revision: Union[str, Sequence[str], None] = '590ff7d8fd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostico',
    sa.Column('analise_mecanico', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('quilometragem', sa.Integer(), nullable=False),
    sa.Column('avarias_latarias', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('nivel_combustivel', sa.Enum('ALTO', 'MEDIO', 'BAIXO', name='nivelcombustivel'), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordemservico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordem_servico_id')
    )
    op.create_table('pagamento',
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('DINHEIRO', 'PIX', 'CREDITO', 'DEBITO', name='formapagamento'), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordemservico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamento_data'), 'pagamento', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamento_data'), table_name='pagamento')
    op.drop_table('pagamento')
    op.drop_table('diagnostico')
    # ### end Alembic commands ###
