"""cria_tabela_peca_servico_veiculo

Revision ID: afe83effcd7b
Revises: 8d1dbaea5a4e
Create Date: 2026-10-02 15:24:05.574901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'afe83effcd7b'
down_revision: Union[str, Sequence[str], None] = '8d1dbaea5a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peca',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peca_nome'), 'peca', ['nome'], unique=False)
    op.create_table('servico',
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servico_descricao'), 'servico', ['descricao'], unique=False)
    op.create_table('veiculo',
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('combustivel', sa.Enum('GASOLINA', 'ALCOOL', 'FLEX', 'HIBRIDO', 'DIESEL', 'ELETRICO', name='combustivelveiculo'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculo_placa'), 'veiculo', ['placa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculo_placa'), table_name='veiculo')
    op.drop_table('veiculo')
    op.drop_index(op.f('ix_servico_descricao'), table_name='servico')
    op.drop_table('servico')
    op.drop_index(op.f('ix_peca_nome'), table_name='peca')
    op.drop_table('peca')
    # ### end Alembic commands ###
