"""adicionando_flag_de_aprovacao

Revision ID: d576a854b2b8
Revises: c0f547693aac
Create Date: 2026-10-02 19:32:00.362629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd576a854b2b8'
down_revision: Union[str, Sequence[str], None] = 'c0f547693aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostico', sa.Column('aprovado_cliente', sa.Boolean(), nullable=False))
    op.add_column('itempeca', sa.Column('aprovado', sa.Boolean(), nullable=False))
    op.add_column('itemservico', sa.Column('aprovado', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemservico', 'aprovado')
    op.drop_column('itempeca', 'aprovado')
    op.drop_column('diagnostico', 'aprovado_cliente')
    # ### end Alembic commands ###
