"""cria_tabela_mecanico

Revision ID: f0d36d993e55
Revises: 47e764a440a2
Create Date: 2026-10-02 14:51:25.329706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0d36d993e55'
down_revision: Union[str, Sequence[str], None] = '47e764a440a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mecanico',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('especialidade', sa.Enum('MECANICA_GERAL', 'INJECAO_ELETRONICA', 'SUSPENSAO_FREIOS', 'CAMBIO_AUTOMATICO', 'AR_CONDICIONADO', 'MOTOR_RETIFICA', name='especialidademecanico'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mecanico_nome'), 'mecanico', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mecanico_nome'), table_name='mecanico')
    op.drop_table('mecanico')
    # ### end Alembic commands ###
